### PR TITLE
4 third algorithm

### PR DESCRIPTION
**Pull request by Jacquelinereverand**
idrk what to write you all know how to test this sry

### CODE REVIEW

**Comment by andrew-wagner89** [comment]
looks good to me

**Comment by jamesvclements** [comment]
I'm going to merge 5-sixth-alg in to this

**Comment by jamesvclements** [comment]
The classroom sizes generated are 18, 19, 20, and 21. Should be more even

**Comment by jamesvclements** [comment]
approving and merging - I'm going to submit a new issue to refactor some of this stuff at a future date

**Pull request merged**
