### PR TITLE
#2 kindergarten sort and file structure

### PR DESCRIPTION
**Pull request by andrew-wagner89**
running "node csv_test.js" will test the kindergarten sort with the kindergarten data csv in /mockdata

### CODE REVIEW

**Comment by andrew-wagner89** [comment]
@Jacquelinereverand @acmccuaig @jamesvclements

**Comment by jamesvclements** [comment]
I'm going to update some of the stuff to `es6` to match the rest of the server

**Comment by jamesvclements** [comment]
looks gucci

**Comment by Jacquelinereverand** [comment]
(y)

**Comment by acmccuaig** [comment]
we good

**Pull request merged**
